/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import DAO.HistoricoDAO;
import models.Aluno;
import models.Historico;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import interfaces.DadosCallback;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduarda
 */
public class Form_historico_listagem extends javax.swing.JFrame implements DadosCallback {

    Aluno aluno;
    Historico historico;

    public Form_historico_listagem() {
        initComponents();
        preencherTabela();
    }

    public Form_historico_listagem(Aluno aluno) {
        initComponents();
        preencherTabela();
        this.aluno = aluno;

    }

    public Form_historico_listagem(Aluno aluno, Historico historico) {
        initComponents();
        preencherTabela();
        this.aluno = aluno;
        this.historico = historico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jB_Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Pesos = new javax.swing.JTable();
        jB_Novo_Peso = new javax.swing.JButton();
        jB_Editar_Peso = new javax.swing.JButton();
        jB_Excluir_Peso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jT_Campo_Pesquisa = new javax.swing.JTextField();
        jB_Lupa = new javax.swing.JButton();
        jB_Listar_Todos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 51, 153));
        jPanel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Histórico de Pesos");

        jB_Voltar.setBackground(new java.awt.Color(255, 204, 204));
        jB_Voltar.setForeground(new java.awt.Color(255, 51, 153));
        jB_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-voltar-35.png"))); // NOI18N
        jB_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jB_Voltar)
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jB_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jT_Pesos.setBackground(new java.awt.Color(255, 204, 255));
        jT_Pesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Aluno", "Nome", "Data Pesagem", "Altura", "Peso Inicial", "Novo Peso", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_Pesos.setSelectionBackground(new java.awt.Color(255, 102, 204));
        jScrollPane1.setViewportView(jT_Pesos);

        jB_Novo_Peso.setBackground(new java.awt.Color(255, 51, 153));
        jB_Novo_Peso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Novo_Peso.setText("Novo");
        jB_Novo_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Novo_PesoActionPerformed(evt);
            }
        });

        jB_Editar_Peso.setBackground(new java.awt.Color(255, 51, 153));
        jB_Editar_Peso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Editar_Peso.setText("Editar");
        jB_Editar_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Editar_PesoActionPerformed(evt);
            }
        });

        jB_Excluir_Peso.setBackground(new java.awt.Color(255, 51, 153));
        jB_Excluir_Peso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Excluir_Peso.setText("Excluir");
        jB_Excluir_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Excluir_PesoActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar por Nome do aluno:");

        jT_Campo_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Campo_PesquisaActionPerformed(evt);
            }
        });

        jB_Lupa.setBackground(new java.awt.Color(255, 51, 153));
        jB_Lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lupa-25.png"))); // NOI18N
        jB_Lupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LupaActionPerformed(evt);
            }
        });

        jB_Listar_Todos.setBackground(new java.awt.Color(255, 51, 153));
        jB_Listar_Todos.setText("Listar todos");
        jB_Listar_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Listar_TodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jB_Novo_Peso)
                        .addGap(99, 99, 99)
                        .addComponent(jB_Editar_Peso)
                        .addGap(114, 114, 114)
                        .addComponent(jB_Excluir_Peso)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jT_Campo_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Lupa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_Listar_Todos)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jB_Lupa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jT_Campo_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jB_Listar_Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Novo_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Editar_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Excluir_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VoltarActionPerformed
        Menu mn = new Menu();
        this.dispose(); //fecha o frame
        mn.setVisible(true);
    }//GEN-LAST:event_jB_VoltarActionPerformed

    private void jB_Novo_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Novo_PesoActionPerformed
        Form_historico fh = new Form_historico(aluno);
        fh.setCallback(this); // Configura o callback
        fh.setVisible(true);
        fh.ocultarBotaoAtualizar();
        
    }//GEN-LAST:event_jB_Novo_PesoActionPerformed

    private void jB_Editar_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Editar_PesoActionPerformed
        int opcao = jT_Pesos.getSelectedRow();
        if (opcao >= 0) {

            Historico h = new Historico();
            h.setIdhist(Integer.parseInt(jT_Pesos.getValueAt(opcao, 6).toString()));
            h.setPeso(Float.parseFloat(jT_Pesos.getValueAt(opcao, 5).toString()));
            h.setDataHist(jT_Pesos.getValueAt(opcao, 2).toString());

            Aluno a = new Aluno();
            a.setNome(jT_Pesos.getValueAt(opcao, 1).toString());
            a.setAltura(Float.parseFloat(jT_Pesos.getValueAt(opcao, 3).toString()));
            a.setIdal(Integer.parseInt(jT_Pesos.getValueAt(opcao, 0).toString()));
            a.setPeso(Float.parseFloat(jT_Pesos.getValueAt(opcao, 4).toString()));
            h.setAluno(a);

            Form_historico fh = new Form_historico(a, h);
            fh.setDadosCallback(this);
            fh.setVisible(true);
            fh.ocultarBotaoSelecionarAluno();
            fh.ocultarBotaoCadastrar();

        }
    }//GEN-LAST:event_jB_Editar_PesoActionPerformed

    private void jB_Excluir_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Excluir_PesoActionPerformed
        int opcao = jT_Pesos.getSelectedRow();
        if (opcao >= 0) {
            Historico h = new Historico();
            h.setIdhist(Integer.parseInt(jT_Pesos.getValueAt(opcao, 6).toString()));

            HistoricoDAO histdao = new HistoricoDAO();
            histdao.excluir(h);
            preencherTabela();
        }

    }//GEN-LAST:event_jB_Excluir_PesoActionPerformed

    private void jB_LupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LupaActionPerformed
        String valor = jT_Campo_Pesquisa.getText();
        preencherTabela(valor);

    }//GEN-LAST:event_jB_LupaActionPerformed

    private void jB_Listar_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Listar_TodosActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jB_Listar_TodosActionPerformed

    private void jT_Campo_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Campo_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Campo_PesquisaActionPerformed
    public void preencherTabela() {
        HistoricoDAO histdao = new HistoricoDAO();
        List<Historico> lista = histdao.listarHistoricos();
        DefaultTableModel tabela = (DefaultTableModel) jT_Pesos.getModel();
        tabela.setRowCount(0);
        for (Historico h : lista) {
            tabela.addRow(new Object[]{h.getAluno().getIdal(), h.getAluno().getNome(), h.getDataHist(), h.getAluno().getAltura(), h.getAluno().getPeso(), h.getPeso(), h.getIdhist()});
        }
    }

    public void preencherTabela(String nomepesquisa) {
        HistoricoDAO histdao = new HistoricoDAO();
        List<Historico> lista = histdao.buscaNome(nomepesquisa);

        DefaultTableModel tabela = (DefaultTableModel) jT_Pesos.getModel();
        tabela.setRowCount(0);
        for (Historico h : lista) {
            tabela.addRow(new Object[]{h.getAluno().getIdal(), h.getAluno().getNome(), h.getDataHist(), h.getAluno().getAltura(), h.getAluno().getPeso(), h.getPeso(), h.getIdhist()});
        }
    }

    @Override
    public void onCadastroConcluido() {
        preencherTabela();
    }

    @Override
    public void onAtualizacaoConcluida() {
        preencherTabela();
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_historico_listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Editar_Peso;
    private javax.swing.JButton jB_Excluir_Peso;
    private javax.swing.JButton jB_Listar_Todos;
    private javax.swing.JButton jB_Lupa;
    private javax.swing.JButton jB_Novo_Peso;
    private javax.swing.JButton jB_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_Campo_Pesquisa;
    private javax.swing.JTable jT_Pesos;
    // End of variables declaration//GEN-END:variables
}
